extends Level
class_name LevelOne

func play_level() -> void:
	
	yield(self, "main_pulse_timeout")
	yield(self, "main_pulse_timeout")
	yield(self, "main_pulse_timeout")
	spawn_enemy(0)
	yield(self, "main_pulse_timeout")
	yield(self, "main_pulse_timeout")
	yield(self, "main_pulse_timeout")
	spawn_enemy(1)
	spawn_enemy(2)
	yield(self, "main_pulse_timeout")
	yield(self, "main_pulse_timeout")
	queue_speed(1.05)
	spawn_enemy(0)
	yield(self, "main_pulse_timeout")
	spawn_enemy(3)
	spawn_enemy(4)
	yield(self, "main_pulse_timeout")
	yield(self, "main_pulse_timeout")
	queue_speed(1.10)
	spawn_enemy(4)
	spawn_enemy(1)
	spawn_enemy(0)
	yield(self, "main_pulse_timeout")
	yield(self, "main_pulse_timeout")
	spawn_enemy(3)
	yield(self, "main_pulse_timeout")
	spawn_enemy(2)
	yield(self, "main_pulse_timeout")
	queue_speed(1.15)
	spawn_enemy(1)
	yield(self, "main_pulse_timeout")
	yield(self, "main_pulse_timeout")
	spawn_enemy(4)
